### ISSUE TITLE
[PE-D][Tester B] Proper displaying of command usage formats

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-F10-2/tp#192]
The general formatting of command usage throughout the UG does not seem to follow any specific formatting. Perhaps the group may consider the following [documentation style guide](https://developers.google.com/style/code-syntax) by Google. This could be applied to the displaying of the help messages in the help menu of the program as well.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: adenteo/ped#11

**Comment by WilsonLee2000** [comment]
Hi Aden, thank you so much for the insightful comments that can help my team to improve our User Guide! I really appreciate it a lot and am working on the issues that you have highlighted at the moment. :)
